networks:
  internal-network:


services:

 db:
    build: ./images/mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql_container
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
#    restart: always
#    ports:
#      - "3307:3306"
    networks:
      - internal-network

 phpmyadmin:
    image: phpmyadmin:5.1.1
#    restart: always
    container_name: phpmyadmin_container
    ports:
      - "8003:80"
    environment:
      - PMA_ARBITRARY=0
      - PMA_VERBOSE=db
      - PMA_HOSTS=db
      - TZ=Europe/Minsk
    networks:
      - internal-network
    depends_on:
      - db

 web:
    build: ./images/python
    container_name: django_container
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8100"
#    restart: always
    volumes:
      - ./msfo_django/:/code/MSFO
    networks:
      - internal-network
    ports:
      - "8100:8100"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

 redis:
    image: redis:7.2.4-alpine
    container_name: redis_container
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
#    restart: always
    networks:
       - internal-network

 celery:
    build: ./images/python
    container_name: celery_container
    command: python -m celery -A main worker
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - internal-network
    volumes:
      - ./msfo_django/:/code/MSFO
