networks:
  msfo-network:
    external: true


services:

 web:
    build: ./images/python
    container_name: django_container
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8100"
#    restart: always
    volumes:
      - ./msfo_django/:/code/MSFO
    networks:
      - msfo-network
    ports:
      - "8100:8100"
    depends_on:
      redis:
        condition: service_healthy

 redis:
    image: redis:7.2.4-alpine
    container_name: redis_container
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
#    restart: always
    networks:
      - msfo-network

 celery:
    build: ./images/python
    container_name: celery_container
    command: python -m celery -A main worker
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - msfo-network
    volumes:
      - ./msfo_django/:/code/MSFO
