# Generated by Django 5.0.3 on 2024-12-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msfo1', '0002_alter_accountmapping_sorting_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='date_of_debt',
            field=models.DateField(blank=True, null=True),
        ),
    ]
