# Generated by Django 5.0.3 on 2024-12-11 06:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msfo1', '0003_alter_debt_date_of_debt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('year_report', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='debt',
            name='report_file',
            field=models.ForeignKey(default=2000, on_delete=django.db.models.deletion.CASCADE, to='msfo1.reportfile'),
            preserve_default=False,
        ),
    ]
