# Generated by Django 5.0.3 on 2024-12-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msfo1', '0006_alter_currencyrate_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfile',
            name='file_path',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
