# Generated by Django 5.0.3 on 2024-05-10 11:19

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Bill name')),
                ('number', models.CharField(max_length=10, verbose_name='Bill name')),
            ],
        ),
        migrations.CreateModel(
            name='EGIL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('month_index', models.DecimalField(decimal_places=4, max_digits=15, null=True, verbose_name='Month index')),
                ('year_index', models.DecimalField(decimal_places=5, max_digits=15, null=True, verbose_name='Year index')),
                ('start_hyper_index', models.DecimalField(decimal_places=3, max_digits=15, null=True, verbose_name='Start hyperinflation index')),
                ('hyper_index', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Index for hyperinflation')),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Year report')),
                ('result_file', models.FileField(blank=True, null=True, upload_to='static/xlsx/%Y-%m-%d')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time creation')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Material name')),
                ('code', models.DecimalField(decimal_places=0, max_digits=20, verbose_name='Code material')),
                ('measuring', models.CharField(max_length=20, verbose_name='Measuring')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Report name')),
                ('date_write_off', models.DateField(default=datetime.date(2017, 1, 1), verbose_name='Date write off')),
                ('date_necessity', models.DateField(verbose_name='Date necessity')),
                ('date_ig2014', models.DateField(default=datetime.date(2015, 1, 1), verbose_name='Date IG2014')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Store name')),
                ('numbers', models.CharField(max_length=20, verbose_name='Store number')),
            ],
        ),
        migrations.CreateModel(
            name='Entrance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Receipt date')),
                ('count', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Count')),
                ('all_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cost')),
                ('id_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msfo8.bill')),
                ('id_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msfo8.material')),
                ('id_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msfo8.report')),
                ('id_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msfo8.store')),
            ],
        ),
    ]
